services:
  - type: web
    name: mydjaserv
    runtime: python
    buildCommand: "./build.sh && source venv/bin/activate"
    startCommand: "source venv/bin/activate && python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        value: "${SECRET_KEY}"
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        value: "${ALLOWED_HOSTS}"
    healthCheckPath: /
    autoDeploy: true
    domains:
      - mydjango-app.onrender.com
