services:
  - type: web
    name: mydjaserv
    runtime: python
    # Create a virtual environment, activate it, install dependencies, and collect static files.
    buildCommand: >
      python3 -m venv venv &&
      . venv/bin/activate &&
      pip install -r requirements.txt &&
      python3 manage.py collectstatic --noinput
    # Activate the virtual environment, apply migrations, and start Gunicorn.
    startCommand: >
      . venv/bin/activate &&
      python3 manage.py migrate &&
      gunicorn forge.wsgi:application --timeout 120 --workers 4 --preload
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        value: "${SECRET_KEY}"
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        value: "${Render}"
      - key: TERM
        value: dumb
    healthCheckPath: /
    autoDeploy: true
    domains:
      - http://stf-trial.onrender.com/
