services:
  - type: web
    name: django-app
    env: python
    buildCommand: ./build.sh # Run the build script for setup
    startCommand: python -m gunicorn Work.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: settings.production
      - key: SECRET_KEY
        sync: true
      - key: DB_NAME
        sync: true
      - key: DB_USER
        sync: true
      - key: DB_PASSWORD
        sync: true
      - key: DB_HOST
        sync: true
      - key: DB_PORT
        value: "5432"
      - key: ALLOWED_HOSTS
        value: "yourdomain.com"
