services:
  - type: web
    name: mydjaserv
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: >-
      python manage.py migrate &&
      gunicorn myproject.wsgi:application --timeout 120 --workers 4 --preload
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        value: "${SECRET_KEY}"
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        value: "${ALLOWED_HOSTS}"
    healthCheckPath: /
    autoDeploy: true
    domains:
      - mydjango-app.onrender.com
