services:
  - type: web
    name: my-django-app
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn my_django_project.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: actual_secret_key_here
      - key: DATABASE_URL
        fromDatabase:
          name: my-database
          property: connectionString
