services:
  - type: web
    name: django-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn Work.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: settings.production
      - key: SECRET_KEY
        sync: true
      - key: DB_NAME
        sync: true
      - key: DB_USER
        sync: true
      - key: DB_PASSWORD
        sync: true
      - key: DB_HOST
        sync: true
      - key: DB_PORT
        value: "5432"
      - key: ALLOWED_HOSTS
        value: "yourdomain.com"
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: DEBUG
        value: "false"
      - key: DATABASE_URL
        sync: true
      - key: DATABASE_CONN_MAX
        value: "20"
      - key: DATABASE_CONN_MIN
        value: "5"
      - key: PORT
        value: "10000"
      - key: CHANNEL_LAYERS
        value: "redis://:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/1"
      - key: REDIS_TIMEOUT
        value: "3600"
      - key: REDIS_POOL_MAX
        value: "10"
      - key: DJANGO_WHITENOISE
        value: "true"
      - key: STATICFILES_STORAGE
        value: "whitenoise.storage.CompressedManifestStaticFilesStorage"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://mydjango-app.onrender.com,https://swifttalentforge.com,https://www.swifttalentforge.com,https://stf-trial.onrender.com"
      - key: DJANGO_SECURE_HSTS_SECONDS
        value: "31536000"
      - key: DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS
        value: "true"
      - key: DJANGO_SECURE_HSTS_PRELOAD
        value: "true"

    healthCheckPath: "/health/"
    autoDeploy: true
    domains:
      - mydjango-app.onrender.com
      - swifttalentforge.com
      - www.swifttalentforge.com
      - stf-trial.onrender.com
