name: Deploy to Render

on:
  push:
    branches:
      - main  # Change this to your deployment branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deployment
        run: |
          curl -X POST "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ https://api.render.com/deploy/srv-cusfmtfnoe9s738upb10?key=Hw8A1myMNEU }}
